#+TITLE: The PowerStrike project

#+begin_src
  ___               _     _ _           _             _   _
 / _ \ _ __   ___  | |__ (_) |_    __ _| |_    __ _  | |_(_)_ __ ___   ___
| | | | '_ \ / _ \ | '_ \| | __|  / _` | __|  / _` | | __| | '_ ` _ \ / _ \
| |_| | | | |  __/ | | | | | |_  | (_| | |_  | (_| | | |_| | | | | | |  __/
 \___/|_| |_|\___| |_| |_|_|\__|  \__,_|\__|  \__,_|  \__|_|_| |_| |_|\___|
#+end_src

* Welcome!
Somehow you reached this site. Contratulations! We are developing a system to measure and transmit power output from MMA/boxing gloves. This is very interesting information that is currently not used in striking sports as MMA, boxing and kickboxing. At this moment we are in alpha stage and focussing on a robust way to add pressure sensors to MMA gloves and show live output to a mobile phone with some gamification of course, otherwise it would be too boring.

** Status of our project

Milestones:
 - [X] Live measurement of impact with pressure sensor. Arduino setup.
 - [X] Connecting several pressure sensors.
 - [X] Adding features for protyping: LCD screen and beeper for output to user.
 - [X] Addition of gamification. Measure and store maximum power of a striek and send confetti or encouragment by text and sound.
 - [X] Adding wifi options: connect with mobile to PowerStrike via local WIFI or directly to Access Point of PowerStrike.

Next steps, our TODO list:
 - [ ] Test the MMA glove with pressure sensors in the dojo. Test the robustness of the MMA gloves and presure connectors and wiring to the controller.
 - [ ] Miniaturization of the detector/controller hardware.
 - [ ] This list will grow during development, step by step.


* PowerStrike use cases
We are in alpha stage but we see a lot of possibilities for our product, not limited to:

** MMA/boxing/kickboxing organization
Show the live power output of strikes of fighters during a fight. For instance plotting energy bars of the amount of absorbed strikes and landed strikes per figher. More gamification during live fights will bring in new audiences. All kinds of stats can be plotted and compared.

** Betting outlets
Imagine the hypothetical world where Tyson Fury will fight Mike Tyson. Which Tyson will dish out the hardest hit? Might be worth a bet :-)

** Martial arts enthousiasts
Gamification to encourage solo bag training. Before training set goals as intensity and/or power and gamify it. The physical progress can be monitored over time. Create tabata workout etc.
The real nerds, I mean the devs of this project :-), can get feedback how strikes are landed. First knuckles versus the Jack Dempsey power line (middle knuckles).

* Contact information
🥊 Hit us up!

  - Technical questions: [[walter@powerstrike.nl][email]]
